### ISSUE TITLE
Add Whirlpool GUI

### ISSUE THREAD

**Issue by Crazyk031** [DesobedienteTecnologico/dtails#12]
[Whirlpool GUI](https://code.samourai.io/whirlpool/whirlpool-gui) would be an excellent addition to the tool. Enabling you to privately & securely access your whirlpool server or mixing on the device increasing chances of remixes compared to using Whirlpool on an Android device.

**Comment by DesobedienteTecnologico** [comment]
I have been working on it yesterday.

![image](https://github.com/DesobedienteTecnologico/dtails/assets/52879067/3ce43568-b87b-44a1-a6a6-dc0658433ef8)


I'm facing some issues with the CLI_API.

Do you have any idea what could be?

I already allow the port 8899 connections from firewall and still.

Regards.

**Comment by DesobedienteTecnologico** [comment]
Issue solved. Soon the PR and merged! :)

**Comment by DesobedienteTecnologico** [comment]
Merged. https://github.com/DesobedienteTecnologico/dtails/pull/15

Closing the Issue. Regards! :)
