### ISSUE TITLE
Persistent Sparrow Wallet

### ISSUE THREAD

**Issue by MeisterEdersCarpentry** [DesobedienteTecnologico/dtails#13]
For [Sparrow](https://github.com/sparrowwallet/sparrow) on dtails, it should be possible to make all the wallet data persistent
(Wallet, as well as conf. files). After restart, the software would find the actual wallet files, as well as the config for your server etc. by itself.

**Comment by DesobedienteTecnologico** [comment]
I will definitely look at that these days.
