### ISSUE TITLE
Installation aborting is not safe

### ISSUE THREAD

**Issue by btclinux** [DesobedienteTecnologico/dtails#16]
If you try to abort installation process and try to remove dtails directory it can crash for some reason your system environment (console stop working for example, unable to reboot etc.)

**Comment by DesobedienteTecnologico** [comment]
Hi,

If you stop for some reason the process. Please, start **./dtails.py** again.

It will show you a new button to remove everything and reset mount points in case were mounted.

![image](https://github.com/DesobedienteTecnologico/dtails/assets/52879067/f1adf19b-b732-498b-a1b2-bd06a0899784)

Code:

1. https://github.com/DesobedienteTecnologico/dtails/blob/main/src/commands.py#L96-L99
2. https://github.com/DesobedienteTecnologico/dtails/blob/main/src/commands.py#L55-L64

Regards.

**Comment by DesobedienteTecnologico** [comment]
Solved
