### ISSUE TITLE
Add Seed Tool 

### ISSUE THREAD

**Issue by BitcoinQnA** [DesobedienteTecnologico/dtails#2]
[Seed Tool](https://t.co/vWGVbqUxkP) seems like the perfect addition to this. It's an updated and improved version of Ian Coleman with lots of explainers and additional tools. 

Live demo [here](https://bitcoiner.guide/seed).

**Comment by DesobedienteTecnologico** [comment]
SeedTool is already in after this PR:
https://github.com/DesobedienteTecnologico/dtails/pull/6

Close it if you think all is already done.

Regads! :)

**Comment by DesobedienteTecnologico** [comment]
Closing this Issue,. PR was merge and all is fully working.
