### ISSUE TITLE
Add Bitcoin Core

### ISSUE THREAD

**Issue by DesobedienteTecnologico** [DesobedienteTecnologico/dtails#26]
As I got this Idea https://github.com/DesobedienteTecnologico/dtails/discussions/25#discussion-5769352 from @RealCocoArdo I will create this issue to keep track and add it into DTails.

**Comment by v41bis** [comment]
hi I opened a PR with Bitcoin Core added, i am not so skilled so I don't know if it's like you want it but it should be ok.
happy to contribute if it will be merged, will continue to experiment on DTails for sure, perfect tool

**Comment by DesobedienteTecnologico** [comment]
Hi! Thanks for your contribution!

Let's continue this conversation in https://github.com/DesobedienteTecnologico/dtails/pull/32 instead. Just few little details need to be added to be ready to Merge.

**Comment by DesobedienteTecnologico** [comment]
Closing because PR https://github.com/DesobedienteTecnologico/dtails/pull/32 was already merged.
