### ISSUE TITLE
Having trouble getting it to work consistently

### ISSUE THREAD

**Issue by AZIPPO** [DesobedienteTecnologico/dtails#35]
it seems to build fine but then in the last stage when I get to burn it to USB it returns this after a very brief burn. Seeing some improvements with tails 20 instead of 22.

` Formating device... 
Error: Could not stat device /dev/sd - No such file or directory.
Error: Could not stat device /dev/sd - No such file or directory.
Error: Could not stat device /dev/sd - No such file or directory.
Error: Could not stat device /dev/sd - No such file or directory.
Error: Could not stat device /dev/sd - No such file or directory.
Error: Could not stat device /dev/sd - No such file or directory.
mkfs.fat 4.1 (2017-01-24)
mkfs.fat: unable to open /dev/sd1: No such file or directory
 Copying files to device... 
mkdir: cannot create directory ‘mount_p’: File exists
mount: /home/mesh/dtails/mount_p: special device /dev/sd1 does not exist.
umount: mount_p: not mounted.
 Installed...
Done!

**Comment by DesobedienteTecnologico** [comment]
If you run DTails again, it will show you a new button from which you can remove everything done.

Once you have done that, please [do this](https://github.com/DesobedienteTecnologico/dtails/issues/9#issuecomment-1532089516) and send me the needed back here.

To me, seems like the flash drive you are using do not have any partition on it. You can try create a new partition with GParted for example. Then do it again.

**Comment by AZIPPO** [comment]
Thanks. had one USB that flashed strangely but have managed to repartition it smaller with success. I managed to get DTails to work by using an older version of linux as above. When I do my next round of them, which might be a while off, I will send you the details as above. Thanks !
