### ISSUE TITLE
update sparrow wallet

### ISSUE THREAD

**Issue by rvcesar** [DesobedienteTecnologico/dtails#39]
estaba usando tu herramienta y me di cuenta que no esta actualizada la versión dado que la que usas es url: 

https://github.com/sparrowwallet/sparrow/releases/download/1.9.1/sparrow-1.9.1-x86_64.tar.gz

y url la actualizada es:

https://github.com/sparrowwallet/sparrow/releases/download/2.0.0/sparrow-2.0.0-x86_64.tar.gz

seria grande que los usuarios puedan introducir los links actualizados en caso que tu no puedas, para así usar aplicaciones actualizadas al momento de construir la imagen...

sin nada mas que agregar, un abrazo...

rvcesar.

**Comment by DesobedienteTecnologico** [comment]
Gracias por tu mensaje. He actualizado todos los paquetes: https://github.com/DesobedienteTecnologico/dtails/commit/15023434d0b9aab05f4d87048e3f93bc7475cff8

Si el dia de mañana necesitas actualizar una versión en concreto, podrás hacerlo manualmente modificando el archivo **src/installer.py** . Saludos :)
