### ISSUE TITLE
Add Border Wallets

### ISSUE THREAD

**Issue by microchad** [DesobedienteTecnologico/dtails#7]
[Border Wallets](https://borderwallets.com) would make a great addition to this fine tool. Border Wallets allow users to create secure, memorable, evil maid-resistant seed phrases, and runs as a standalone tool [here](https://github.com/microchad/borderwallets/releases/) and as an integrated feature within [Sparrow Wallet](https://github.com/sparrowwallet/sparrow/releases).

Demonstration video [here](https://www.youtube.com/watch?v=wHQrvCGVkTw&t=1s).

**Comment by DesobedienteTecnologico** [comment]
Already Merge and working.

Probably the logo do not look that well due the shape. In case you change it in the future just let me know.

Feel free to close this issue.

Regards! :)
